window.grammarBank = [
  { grammar: "다가", meaning: "-yotib" },
  { grammar: "고 나서", meaning: "-ib bo‘lib" },
  { grammar: "ㄴ/은/는데", meaning: "① lekin ② -da" },
  { grammar: "(으)려고", meaning: "-ishi uchun" },
  { grammar: "(으)려면", meaning: "-moqchi bo‘lsa" },
  { grammar: "느라고", meaning: "-deb" },
  { grammar: "아야/어야", meaning: "-sagina" },
  { grammar: "ㄹ/을까 봐(서)", meaning: "-mi ekan deb" },
  { grammar: "거나", meaning: "-yoki" },
  { grammar: "자마자", meaning: "-gan zahoti" },
  { grammar: "ㄹ/을수록", meaning: "-sayin" },
  { grammar: "아서/어서", meaning: "① -gani uchun ② -ib" },
  { grammar: "아서/어서 그런지", meaning: "-ganigami" },
  { grammar: "더니", meaning: "-gandi" },
  { grammar: "ㄹ/을지", meaning: "-ligi(ni), -ish(ni)" },
  { grammar: "(으)면서", meaning: "-ib" },
  { grammar: "(으)니까", meaning: "-gani uchun" },
  { grammar: "(으)면", meaning: "-sa" },
  { grammar: "든지", meaning: "-sa ham" },
  { grammar: "ㄴ/은/는 데다가", meaning: "bilan bir qatorda" },
  { grammar: "ㄴ/은/는 대신", meaning: "o‘rniga" },
  { grammar: "아도/어도", meaning: "-sa ham" },
  { grammar: "는 김에", meaning: "-ganda" },
  { grammar: "는 바람에", meaning: "-gani uchun (salbiy)" },
  { grammar: "ㄴ/은 채로", meaning: "-gan holda" },
  { grammar: "ㄴ/은/는 덕분에", meaning: "sharofati bilan" },
  { grammar: "도록", meaning: "① -ish uchun ② -guncha" },
  { grammar: "기에/길래", meaning: "-ganiga" },
  { grammar: "더라도", meaning: "-sa ham" },
  { grammar: "다가 보면", meaning: "-ayversa" },
  { grammar: "아/어 놓다/두다", meaning: "-ib qo‘ymoq" },
  { grammar: "기로 했다", meaning: "-ishga qaror qilmoq" },
  { grammar: "(으)면 되다", meaning: "-sa bo‘lmoq" },
  { grammar: "게 하다", meaning: "-qildirmoq" },
  { grammar: "게 되다", meaning: "-digan bo‘lmoq" },
  { grammar: "ㄴ/은 적이 있다", meaning: "-ib ko‘rgan" },
  { grammar: "아/어 있다", meaning: "-ib turmoq" },
  { grammar: "아/어 가다", meaning: "-ib bormoq" },
  { grammar: "아/어 오다", meaning: "-ib kelmoq" },
  { grammar: "ㄴ/은/는 셈이다", meaning: "-di hisobi" },
  { grammar: "ㄹ/을 뻔했다", meaning: "-sal qoldi" },
  { grammar: "F + 나 보다 | S + ㄴ/은가 보다", meaning: "-ga o‘xshamoq" },
  { grammar: "기 마련이다", meaning: "-ishi aniq" },
  { grammar: "ㄴ/은/는 모양이다", meaning: "-ga o‘xshamoq" },
  { grammar: "아/어 버리다", meaning: "-ib tashladi" },
  { grammar: "아/어 보이다", meaning: "-ko‘rinmoq" },
  { grammar: "ㄴ/은/는 척하다", meaning: "-dek tutmoq" },
  { grammar: "ㄹ/을지도 모르다", meaning: "-ishi mumkin" },
  { grammar: "ㄹ/을 리가 없다", meaning: "-ishi mumkin emas" }
];
