const wordBank = [
    { korean: "심리학자", uzbek: "psixolog" },
    { korean: "도전", uzbek: "da’vat, undov" },
    { korean: "요구", uzbek: "talab" },
    { korean: "건조하다", uzbek: "quruq" },
    { korean: "유전적", uzbek: "irsiy, genetik" },
    { korean: "공사", uzbek: "qurilish" },
    { korean: "굵다", uzbek: "qalin" },
    { korean: "본능", uzbek: "instinkt (mavjudodlar tabiiy ravishda qiladigan harakati)" },
    { korean: "밀려오다", uzbek: "uyulib kelmoq" },
    { korean: "드물다", uzbek: "kamyob, kamnamo" },
    { korean: "옹호하다", uzbek: "himoya qilmoq  (인권을 \\~)" },
    { korean: "감격", uzbek: "juda ta’sirlanish" },
    { korean: "심리", uzbek: "psixologiya" },
    { korean: "평소", uzbek: "odatiy" },
    { korean: "탁하다", uzbek: "loyqa (물), dag’al, yo’g’on (목소리), iflos (공기)" },
    { korean: "수술", uzbek: "jarrohlik operatsiyasi" },
    { korean: "마법", uzbek: "sehr" },
    { korean: "숙이다", uzbek: "bukmoq" },
    { korean: "전통", uzbek: "milliy" },
    { korean: "그늘", uzbek: "soya" },
    { korean: "복권", uzbek: "lotoreya chiptasi" },
    { korean: "이국적", uzbek: "egzotik, ajib, g’ayrioddiy" },
    { korean: "숨기다", uzbek: "yashirmoq" },
    { korean: "완벽하다", uzbek: "mukammal" },
    { korean: "소식", uzbek: "1. yangilik 2. kam yeyish" },
    { korean: "망치다", uzbek: "buzmoq, barbod qilmoq" },
    { korean: "몹시", uzbek: "juda" },
    { korean: "희미하다 = 흐릿하다", uzbek: "xira, tiniq emas" },
    { korean: "긋다", uzbek: "chizmoq" },
    { korean: "불감증", uzbek: "befarqlik, xis qilmaslik" },
    { korean: "문병하다", uzbek: "bemorni ko'rgani bormoq" },
    { korean: "경로", uzbek: "1. yo'lak 2. yo'l, usul" },
    { korean: "감동", uzbek: "taassurot" },
    { korean: "한가하다", uzbek: "bo’sh bo’lmoq / bekor bo’lmoq" },
    { korean: "중단", uzbek: "to'xtatish" },
    { korean: "결핍 = 부족", uzbek: "yetishmaslik (비타민의 결핍)" },
    { korean: "섞다", uzbek: "aralashtirmoq" },
    { korean: "고집이 세다", uzbek: "juda qaysar" },
    { korean: "직원", uzbek: "ishchi" },
    { korean: "왕복", uzbek: "borib-kelish" },
    { korean: "의외로", uzbek: "kutilmaganda, kutilgandan" },
    { korean: "그립다", uzbek: "sog’inmoq" },
    { korean: "계층", uzbek: "sinf, tabaqa (odamlarning jamiyatdagi)" },
    { korean: "기여하다", uzbek: "hissa qo'shmoq" },
    { korean: "터지다", uzbek: "yorilmoq" },
    { korean: "물려받다", uzbek: "meros olmoq" },
    { korean: "습기", uzbek: "namlik" },
    { korean: "이민자", uzbek: "muhojir (immigrant)" },
    { korean: "방향", uzbek: "yo’nalish" },
    { korean: "쫓아내다", uzbek: "1. haydab yubormoq 2. quvmoq" },
    { korean: "머릿결 = 머리카락", uzbek: "soch" },
    { korean: "진행자", uzbek: "boshlovchi" },
    { korean: "실용화하다", uzbek: "amaliyotga tadbiq qilmoq" },
    { korean: "반짝이다", uzbek: "yonib o'chmoq (chiroq va boshqalar)" },
    { korean: "실외", uzbek: "tashqari " },
    { korean: "풍습", uzbek: "urf-odat" },
    { korean: "전달하다", uzbek: "yetkazmoq" },
    { korean: "원망하다", uzbek: "g’azablanmoq" },
    { korean: "돌다", uzbek: "aylanmoq" },
    { korean: "당분간", uzbek: "biroz vaqt, xozircha, vaqtincha" },
    { korean: "지역", uzbek: "hudud" },
    { korean: "약화시키다", uzbek: "zaiflashtirmoq" },
    { korean: "헤매다", uzbek: "aylanib yurmoq" },
    { korean: "신뢰하다 = 믿다", uzbek: "ishonmoq" },
    { korean: "여러 종류 = 여러 가지", uzbek: "har xil" },
    { korean: "유연성", uzbek: "moslashuvchanlik" },
    { korean: "공모하다", uzbek: "1. (biror narsada) jamoat qatnashishini taklif" },
    { korean: "자기 자신", uzbek: "o’z o’zi" },
    { korean: "무덥다", uzbek: "issiq va dim" },
    { korean: "미혼", uzbek: "turmush qurmagan" },
    { korean: "상황", uzbek: "holat, vaziyat" },
    { korean: "멸종", uzbek: "qirilib ketish " },
    { korean: "심다", uzbek: "ekmoq" },
    { korean: "시상식", uzbek: "taqdirlash marosimi" },
    { korean: "공급하다", uzbek: "ta'minlamoq" },
    { korean: "혼내다", uzbek: "tanbeh bermoq, urushib qo’ymoq" },
    { korean: "빼내다", uzbek: "olmoq, chiqarib olmoq" },
    { korean: "닿다", uzbek: "1. tegmoq 2. yetib bormoq" },
    { korean: "돌아가다", uzbek: "1. qaytib ketmoq 2. aylanmoq (chapga/o'ngga) 3. vafot etmoq" },
    { korean: "직장인", uzbek: "ishchi" },
    { korean: "답사", uzbek: "1. tekshiruv 2. javob" },
    { korean: "놀리다", uzbek: "o’ynatmoq" },
    { korean: "설문", uzbek: "so’rovnoma" },
    { korean: "제거", uzbek: "olib tashlash (장애물을 모두 \\~하다)" },
    { korean: "셋이서", uzbek: "uch bo’lib" },
    { korean: "뚜렷하다", uzbek: "aniq, tiniq, aniq-ravshan" },
    { korean: "행태", uzbek: "xatti-harakati" },
    { korean: "기둥", uzbek: "ustun" },
    { korean: "열리다", uzbek: "1. ochilmoq 2. bo'lib o'tmoq (tadbir va hkz)" },
    { korean: "조종사", uzbek: "uchuvchi" },
    { korean: "한숨을 쉬다", uzbek: "xo'rsinmoq" },
    { korean: "찢기다 = 찢어지다", uzbek: "yirtilmoq" },
    { korean: "애완동물", uzbek: "uy hayvoni" },
    { korean: "잘못", uzbek: "xato" },
    { korean: "거만하다", uzbek: "kekkaygan " },
    { korean: "기관", uzbek: "1. tashkilot 2. (inson) a'zo" },
    { korean: "줄어들다", uzbek: "qisqarmoq, kamaymoq" },
    { korean: "점차", uzbek: "asta-sekin" },
    { korean: "이만큼", uzbek: "mana buncha" },
    { korean: "실리다", uzbek: "1. yuklanmoq 2. bosib chiqarilmoq" },
    { korean: "소재", uzbek: "1. material 2. asos (kino va asarlar mavzu qilib" },
    { korean: "언론", uzbek: "ommaviy axborot" },
    { korean: "화합", uzbek: "1. birdamlik 2. birikma" },
    { korean: "예술품", uzbek: "san'at asari" },
    { korean: "이용하다", uzbek: "foydalanmoq" },
    { korean: "엄청나다 = 대단하다", uzbek: "katta" },
    { korean: "원자력발전소", uzbek: "atom elektr stansiyasi" },
    { korean: "맡다", uzbek: "1. xidlamoq 2. zimmasiga olmoq" },
    { korean: "관람객", uzbek: "tomoshabin" },
    { korean: "지연하다 = 지체하다", uzbek: "kechiktirmoq" },
    { korean: "해양", uzbek: "okean" },
    { korean: "학점", uzbek: "baho" },
    { korean: "불경기", uzbek: "turg’unlik, iqtisodiy tanazzul" },
    { korean: "닫히다", uzbek: "yopilmoq" },
    { korean: "결론", uzbek: "xulosa" },
    { korean: "훔치다", uzbek: "o’g’irlamoq" },
    { korean: "결국", uzbek: "oxir-oqibatda, natijada" },
    { korean: "모습", uzbek: "qiyofa, ko’rinish" },
    { korean: "거리", uzbek: "1. yo’l 2. masofa" },
    { korean: "독창성", uzbek: "yaratuvchanlik" },
    { korean: "슬프다", uzbek: "xafa bo'lmoq" },
    { korean: "연료", uzbek: "yonilg'i" },
    { korean: "조사", uzbek: "tekshiriv" },
    { korean: "인기 요인", uzbek: "asosiy sabab" },
    { korean: "의미", uzbek: "ma’no" },
    { korean: "습성", uzbek: "odat" },
    { korean: "조만간", uzbek: "tez orada" },
    { korean: "숨지다", uzbek: "vafot etmoq" },
    { korean: "영업", uzbek: "ish, savdo" },
    { korean: "음향", uzbek: "ovoz" },
    { korean: "어쩐지", uzbek: "nimagadir" },
    { korean: "괜히", uzbek: "bekorga" },
    { korean: "쓸데없이", uzbek: "(ravish) foydasiz, maqsadsiz" },
    { korean: "굶다", uzbek: "och qolmoq" },
    { korean: "외모", uzbek: "tashqi ko'rinish" },
    { korean: "자료", uzbek: "material" },
    { korean: "맛집", uzbek: "oshxona" },
    { korean: "최신", uzbek: "eng oxirgi (\\~의 뉴스)" },
    { korean: "자세하다", uzbek: "batafsil" },
    { korean: "열람실", uzbek: "o'qish xonasi" },
    { korean: "돌려보내다", uzbek: "qaytarib yubormoq" },
    { korean: "꾸미다", uzbek: "1. bezamoq 2. to’qimoq (uydirma)" },
    { korean: "현대적", uzbek: "zamonaviy" },
    { korean: "구조대", uzbek: "qutqaruv jamoasi" },
    { korean: "말투", uzbek: "gaplash ohangi" },
    { korean: "간파하다", uzbek: "topmoq" },
    { korean: "무려 + son", uzbek: "kamida" },
    { korean: "질량", uzbek: "massa" },
    { korean: "어울리다", uzbek: "1. yarashmoq 2. chiqishmoq (odamlar bilan)" },
    { korean: "빼놓다", uzbek: "1. (guruhdan va hkz) chiqarmoq 2. qoldirib o’tmoq" },
    { korean: "거스르다 = 반대하다", uzbek: "qarshi bo'lmoq" },
    { korean: "적어도", uzbek: "kamida" },
    { korean: "체중 = 몸무게", uzbek: "tana og’irligi" },
    { korean: "디자인", uzbek: "dizayn" },
    { korean: "채식주의자", uzbek: "vegeterian (go’sht maxsulotlarini yemaydigan odam)" },
    { korean: "넘나들다", uzbek: "tez-tez tashrif buyurmoq" },
    { korean: "증정품", uzbek: "bepul sovg'alar" },
    { korean: "더위를 먹다", uzbek: "issiq urmoq" },
    { korean: "당기다", uzbek: "tortmoq" },
    { korean: "슬쩍", uzbek: "1. sezdirmay, zimdan 2. salgina" },
    { korean: "열등감", uzbek: "pastlik hissi (ya'ni o'zini pastdek his qilmoq)" },
    { korean: "일정을 정하다 / 짜다", uzbek: "kun tartibini tuzmoq" },
    { korean: "분리수거", uzbek: "ahlatni ajratish  (쓰레기를 \\~)" },
    { korean: "권유하다", uzbek: "taklif qilmoq" },
    { korean: "넣다", uzbek: "solmoq" },
    { korean: "마찰", uzbek: "1. ishqalanish 2. kelishmovchilik" },
    { korean: "고생", uzbek: "qiyinchilik" },
    { korean: "온도", uzbek: "harorat" },
    { korean: "꿈", uzbek: "1. orzu 2. tush" },
    { korean: "저출산", uzbek: "kam tug'ilish" },
    { korean: "거부하다", uzbek: "rad etmoq" },
    { korean: "나이별", uzbek: "yoshiga qarab" },
    { korean: "공지하다", uzbek: "e'lon qilmoq" },
    { korean: "주목하다", uzbek: "e'tibor bermoq" },
    { korean: "마감", uzbek: "tugatish, oxirgi" },
    { korean: "게시판", uzbek: "e'lonlar taxtasi" },
    { korean: "간절히", uzbek: "1. chin qalbdan 2. kuchli" },
    { korean: "그다지", uzbek: "u darajada" },
    { korean: "갑부", uzbek: "millioner, juda boy" },
    { korean: "문화", uzbek: "madaniyat" },
    { korean: "애완경", uzbek: "xonaki it" },
    { korean: "충분하다", uzbek: "yetarli" },
    { korean: "에어컨", uzbek: "konditsioner" },
    { korean: "긴장하다", uzbek: "asabiylashmoq" },
    { korean: "기도", uzbek: "duo, iltijo" },
    { korean: "한자", uzbek: "Xitoy iroglifi" },
    { korean: "알리다", uzbek: "bildirmoq" },
    { korean: "설득하다", uzbek: "ko’ndirmoq" },
    { korean: "해고하다", uzbek: "bo'shatmoq" },
    { korean: "원리", uzbek: "tamoyil" },
    { korean: "명함", uzbek: "vizitka" },
    { korean: "배려하다", uzbek: "qayg’urmoq " },
    { korean: "불행", uzbek: "baxtsizlik" },
    { korean: "물러서다", uzbek: "1. orqaga yurmoq 2. voz kechmoq" },
    { korean: "마침내", uzbek: "va nixoyat" },
    { korean: "생략하다", uzbek: "tushurib qoldirmoq" },
    { korean: "고수하다", uzbek: "fikrida turib olmoq (의견을 \\~, 관점을 \\~, 입장을 \\~)" },
    { korean: "조정하다", uzbek: "1. to'g'irlamoq 2. yarashtirmoq" },
    { korean: "솔직히 말하면", uzbek: "ochiqchasini aytsam, to’g’risini aytganda" },
    { korean: "줍다", uzbek: "1. pastdan olmoq 2. topib olmoq" },
    { korean: "동굴", uzbek: "g’or" },
    { korean: "기울이다", uzbek: "1. egmoq (고개를, 몸을 \\~) 2. bag’ishlamoq, bor e’tiborini bermoq" },
    { korean: "요이하다", uzbek: "oson" },
    { korean: "보관하다", uzbek: "saqlamoq" },
    { korean: "감격스럽다", uzbek: "kuchli ta’sirlanmoq" },
    { korean: "전업", uzbek: "kasb" },
    { korean: "성인", uzbek: "balog’atga yetgan" },
    { korean: "단순하다", uzbek: "oddiy" },
    { korean: "임시", uzbek: "vaqtincha" },
    { korean: "동료", uzbek: "hamkasb" },
    { korean: "적응력", uzbek: "moslashuvchanlik qobiliyati" },
    { korean: "가무잡잡하다", uzbek: "qoramtir" },
    { korean: "성과", uzbek: "natija" },
    { korean: "상식", uzbek: "umumiy bilim" },
    { korean: "대기 오염", uzbek: "atmosfera ifloslanishi" },
    { korean: "한반도", uzbek: "Koreya yarim oroli" },
    { korean: "공공장소", uzbek: "jamoat joyi" },
    { korean: "향하다", uzbek: "yuzlanmoq" },
    { korean: "대기업", uzbek: "katta karxona" },
    { korean: "논점", uzbek: "masalaning uchi/mohiyati" },
    { korean: "유쾌하다", uzbek: "yoqimli, quvnoq" },
    { korean: "낮잠 (\\~을 자다)", uzbek: "tushlikdan keyingi uyqu (\\~ni uxlamoq)" },
    { korean: "보수적", uzbek: "eskilik tarafdori bo’lgan (konservativ)" },
    { korean: "재활용", uzbek: "qayt ishlab chiqarish" },
    { korean: "액체", uzbek: "suyuq" },
    { korean: "진열", uzbek: "ko'rgazma qilish" },
    { korean: "협상", uzbek: "muzokara" },
    { korean: "발견하다", uzbek: "topmoq" },
    { korean: "반사하다", uzbek: "aks etmoq" },
    { korean: "특유", uzbek: "o'ziga xos" },
    { korean: "한국학", uzbek: "koreyashunoslik" },
    { korean: "보조금", uzbek: "subsidiya" },
    { korean: "마비되다", uzbek: "1. falaj bo'lmoq 2. ishdan chiqmoq" },
    { korean: "전문가", uzbek: "mutaxassis" },
    { korean: "쏘다", uzbek: "otmoq " },
    { korean: "용기", uzbek: "jur'at" },
    { korean: "조건", uzbek: "shart" },
    { korean: "양", uzbek: "1. miqdor 2. qo'y 3. ikkala" },
    { korean: "종종", uzbek: "ba'zan" },
    { korean: "강단", uzbek: "1. tirishqoqlik 2. minbar" },
    { korean: "협조하다", uzbek: "yordamlashmoq" },
    { korean: "시민", uzbek: "fuqaro" },
    { korean: "자기 소개서", uzbek: "o'zini tanishtirish xati" },
    { korean: "흥분하다", uzbek: "quvonmoq" },
    { korean: "가파르다", uzbek: "1. tik 2. keskin" },
    { korean: "증정하다", uzbek: "bermoq, taqdim qilmoq" },
    { korean: "둔하다", uzbek: "1. aqli past 2. sekin (odamlarga nisbatan)" },
    { korean: "수치심", uzbek: "uyat" },
    { korean: "타당성", uzbek: "haqqoniylik" },
    { korean: "산책로", uzbek: "yo'lak" },
    { korean: "부딪치다", uzbek: "to'qnashmoq, duch kelmoq " },
    { korean: "중소기업", uzbek: "o'rta va kichik firma" },
    { korean: "대하다", uzbek: "1. duch kelmoq 2. muomala qilmoq" },
    { korean: "당시", uzbek: "o'sha vaqt" },
    { korean: "남 = 타인", uzbek: "boshqalar" },
    { korean: "귀화하다", uzbek: "mahalliylashmoq" },
    { korean: "장난", uzbek: "hazil, o'yin" },
    { korean: "특이하다", uzbek: "noodatiy, o'ziga xos" },
    { korean: "은혜", uzbek: "yaxshilik" },
    { korean: "지르다", uzbek: "baqirmoq, qichqirmoq" },
    { korean: "껌을 씹다", uzbek: "saqich chaynamoq" },
    { korean: "삶", uzbek: "hayot" },
    { korean: "응답", uzbek: "javob" },
    { korean: "나다", uzbek: "1. chiqmoq 2. yuz bermoq" },
    { korean: "고민하다", uzbek: "xavotirlanmoq" },
    { korean: "현명하다 = 지혜롭다 = 똑똑하다", uzbek: "aqlli" },
    { korean: "변명", uzbek: "bahona" },
    { korean: "떨리다", uzbek: "qaltiramoq" },
    { korean: "우주선", uzbek: "fazo kemasi" },
    { korean: "약화", uzbek: "zaiflashish" },
    { korean: "주연", uzbek: "asosiy qahramon (drama va kinoda)" },
    { korean: "규모", uzbek: "ko'lam, miqdor" },
    { korean: "전체", uzbek: "butun" },
    { korean: "찾아뵈다", uzbek: "tashrif buyurmoq" },
    { korean: "분량", uzbek: "miqdor" },
    { korean: "생중계", uzbek: "jonli efir" },
    { korean: "피로", uzbek: "charchoq " },
    { korean: "일어나다", uzbek: "1. turmoq 2. yuz bermoq" },
    { korean: "빼기", uzbek: "ayirish" },
    { korean: "무게", uzbek: "vazn, og'irlik" },
    { korean: "추론하다", uzbek: "xulosa qilmoq" },
    { korean: "잡아먹다", uzbek: "tutib yemoq" },
    { korean: "바깥", uzbek: "tashqari" },
    { korean: "모양", uzbek: "shakl" },
    { korean: "소화", uzbek: "hazm" },
    { korean: "더위", uzbek: "issiqlik" },
    { korean: "자신감", uzbek: "o’ziga ishonch" },
    { korean: "조언", uzbek: "maslahat" },
    { korean: "안전띠", uzbek: "xavfsizlik kamari" },
    { korean: "여줘보다", uzbek: "so'ramoq (xurmat shakli)" },
    { korean: "전시회", uzbek: "(진열) ko’rgazma" },
    { korean: "모시다", uzbek: "1. (부모를 \\~) xizmat qilmoq 2. (손님을 \\~) kuzatmoq" },
    { korean: "예방하다", uzbek: "oldini olmoq" },
    { korean: "이제", uzbek: "endi" },
    { korean: "매달리다", uzbek: "osilmoq" },
    { korean: "특별하다", uzbek: "maxsus, o’zgacha" },
    { korean: "긍정하다", uzbek: "ma'qullamoq" },
    { korean: "두통", uzbek: "bosh og'rig’i" },
    { korean: "폭발", uzbek: "portlash" },
    { korean: "뭉치다", uzbek: "yig'moq" },
    { korean: "배기가스", uzbek: "zararli gaz (mashina va boshqalardan chiqadigan)" },
    { korean: "꾸짖다", uzbek: "koyimoq, so’kmoq (지각했다고 학생들을 호되게 \\~)" },
    { korean: "거두다", uzbek: "yig’ib olmoq (pul, soliq yoki hosilni)" },
    { korean: "곡선", uzbek: "egri chiziq" },
    { korean: "변변히", uzbek: "yaxshi, yetarlicha" },
    { korean: "어차피", uzbek: "nima bo’lgan taqdirda ham" },
    { korean: "도저히", uzbek: "umuman" },
    { korean: "젊다", uzbek: "yosh" },
    { korean: "지나치게 = 과도하게", uzbek: "o’ta darajada, ortiqcha" },
    { korean: "입시", uzbek: "kirish imtihoni" },
    { korean: "특히", uzbek: "ayniqsa" },
    { korean: "숨", uzbek: "nafas" },
    { korean: "대기실", uzbek: "kutish xonasi" },
    { korean: "거북하다", uzbek: "noqulay xis qilmoq, o'zini yamon xis qilmoq" },
    { korean: "교육", uzbek: "ta’lim" },
    { korean: "대피하다", uzbek: "evakuatsiya qilmoq" },
    { korean: "제시하다", uzbek: "ko’rsatmoq, keltirmoq" },
    { korean: "관람하다", uzbek: "kuzatmoq, tomosha qilmoq" },
    { korean: "분석하다", uzbek: "tahlil qilmoq" },
    { korean: "과음하다", uzbek: "ortiqcha ichmoq (alkogol ichimlarini)" },
    { korean: "오해", uzbek: "xato tushunish" },
    { korean: "투자하다", uzbek: "sarmoya kiritmoq" },
    { korean: "전공", uzbek: "yo'nalish, mutaxassislik" },
    { korean: "적절하다", uzbek: "mos, to'g'ri kelmoq" },
    { korean: "시선을 끌다", uzbek: "nazarini tortmoq" },
    { korean: "유권자", uzbek: "saylovchi" },
    { korean: "성공을 이룩하다", uzbek: "muvaffaqiyatga erishmoq" },
    { korean: "자율", uzbek: "o'z-o'zini boshqaruvchi, avtonimiya" },
    { korean: "무사히", uzbek: "tinch, eson-omon" },
    { korean: "늘", uzbek: "hamisha" },
    { korean: "불만스럽다", uzbek: "qoniqmaslik, ko’ngli to’lmaslik" },
    { korean: "홍보", uzbek: "reklama, ovaza qilish" },
    { korean: "연휴", uzbek: "uzoq dam olish kunlari (chusok va sollal bayramida)" },
    { korean: "소규모", uzbek: "kichkina o’lcham" },
    { korean: "평생", uzbek: "butun umr" },
    { korean: "잠자리", uzbek: "yatoq" },
    { korean: "대형", uzbek: "katta o’lcham" },
    { korean: "국외", uzbek: "chet -el" },
    { korean: "효율성", uzbek: "samaradorlik" },
    { korean: "적립되다", uzbek: "yig’ilmoq (pul)" },
    { korean: "몰다", uzbek: "1. (mashina, ot va hkz) haydamoq 2. (odamni) haydamoq" },
    { korean: "흘러가다", uzbek: "1. oqmoq 2. (시간, 청춘 시대) o’tib bormoq" },
    { korean: "지키다", uzbek: "saqlamoq" },
    { korean: "적성에 맞다", uzbek: "qobiliyatiga mos kelmoq" },
    { korean: "좀처럼", uzbek: "1. har doim 2. osongina" },
    { korean: "상승하다", uzbek: "oshmoq, ko'tarilmoq" },
    { korean: "얼마든지", uzbek: "qancha bo'lsa ham" },
    { korean: "희다", uzbek: "oq" },
    { korean: "신기술", uzbek: "yangi texnologiya" },
    { korean: "감추다", uzbek: "숨기다 = yashirmoq" },
    { korean: "연구소", uzbek: "tadqiqot markazi" },
    { korean: "오류", uzbek: "xato (문법상의 \\~)" },
    { korean: "국가 이미지", uzbek: "milliylik, davlat imiji" },
    { korean: "과격하다", uzbek: "radikal (qarshi)" },
    { korean: "표시", uzbek: "belgi" },
    { korean: "형태", uzbek: "shakl" },
    { korean: "해롭다", uzbek: "zararli" },
    { korean: "깨지다", uzbek: "sinmoq" },
    { korean: "의약품", uzbek: "tibbiy ta'minot" },
    { korean: "환불", uzbek: "qaytarib berish" },
    { korean: "통화하다", uzbek: "telefonda gaplashmoq" },
    { korean: "경쟁하다", uzbek: "raqobatlashmoq" },
    { korean: "마주치다", uzbek: "duch kelmoq" },
    { korean: "뽑다", uzbek: "1. sug’urib olmoq 2. tanlamoq" },
    { korean: "야유회", uzbek: "tabiyat qo'ynida yig'ilish" },
    { korean: "몇몇", uzbek: "bir nechta" },
    { korean: "기념", uzbek: "estalik" },
    { korean: "수여하다", uzbek: "bermoq (상을, 작위를 \\~)" },
    { korean: "토의", uzbek: "muhokama" },
    { korean: "답하다", uzbek: "javob bermoq" },
    { korean: "성별", uzbek: "jinsga qarab" },
    { korean: "친밀도", uzbek: "yaqinlik darajasi" },
    { korean: "근무", uzbek: "ish, xizmat" },
    { korean: "달려가다", uzbek: "yugurib ketmoq, oshiqmoq" },
    { korean: "화면", uzbek: "ekran" },
    { korean: "위로하다", uzbek: "yupatmoq" },
    { korean: "시인", uzbek: "shoir" },
    { korean: "주의를 기울이다", uzbek: "e’tiborli bermoq" },
    { korean: "구분하다", uzbek: "ajratmoq" },
    { korean: "심하다", uzbek: "kuchli, qattiq" },
    { korean: "검색", uzbek: "qidiruv, qidirish" },
    { korean: "돌파구", uzbek: "keskin burilish" },
    { korean: "완전히", uzbek: "mutlaqo" },
    { korean: "관심", uzbek: "qiziqish" },
    { korean: "현장", uzbek: "joy, voqea joyi" },
    { korean: "예상", uzbek: "kutish, kuzatilish" },
    { korean: "기쁨", uzbek: "quvonch" },
    { korean: "그만 …", uzbek: "biror narsa qilishni bas qilmoq (\\~하다, 울다)" },
    { korean: "존재", uzbek: "mavjudligi" },
    { korean: "기분", uzbek: "kayfiyat" },
    { korean: "생각이 들다", uzbek: "fikr kelmoq" },
    { korean: "업무", uzbek: "ish" },
    { korean: "두려움", uzbek: "qo'rquv" },
    { korean: "지위", uzbek: "lavozim, mansab" },
    { korean: "장기적", uzbek: "uzoq muddat" },
    { korean: "홍보하다", uzbek: "reklama qilmoq" },
    { korean: "억제", uzbek: "tiyish (감정, 육욕 \\~)" },
    { korean: "놀라다", uzbek: "hayratlanmoq" },
    { korean: "믿음", uzbek: "ishonch" },
    { korean: "훌룡하다", uzbek: "ajoyib" },
    { korean: "발전시키다", uzbek: "rivojlantirmoq" },
    { korean: "마련하다", uzbek: "tayyorlamoq" },
    { korean: "접다", uzbek: "buklamoq" },
    { korean: "병세", uzbek: "kasalligi " },
    { korean: "물체", uzbek: "obyekt, buyum" },
    { korean: "규율", uzbek: "tartib" },
    { korean: "책임", uzbek: "ma'suliyat" },
    { korean: "조리법", uzbek: "pishirish uslubi" },
    { korean: "작가", uzbek: "(=글쓴이) yozuvchi" },
    { korean: "속이다", uzbek: "aldamoq" },
    { korean: "섞이다", uzbek: "aralashmoq" },
    { korean: "녹지대", uzbek: "yashil hudud" },
    { korean: "연락처", uzbek: "kantakt nomer" },
    { korean: "싣다", uzbek: "1. yuklamoq 2. nashr qilmoq" },
    { korean: "운항", uzbek: "parvoz" },
    { korean: "향수병", uzbek: "uy sog'inchi" },
    { korean: "정확하다", uzbek: "aniq, ravshan" },
    { korean: "기회", uzbek: "imkoniyat" },
    { korean: "우승하다", uzbek: "g’alaba qozonmoq" },
    { korean: "명색", uzbek: "nom" },
    { korean: "뒤늦다", uzbek: "kech qolmoq" },
    { korean: "범행", uzbek: "jinoyat" },
    { korean: "여부", uzbek: "xa yoki yo'q" },
    { korean: "입사하다", uzbek: "ishga kirmoq" },
    { korean: "즉", uzbek: "ya’ni" },
    { korean: "나누기", uzbek: "bo'lish" },
    { korean: "개명", uzbek: "1. yangilanish 2. ismini o'zgartirish" },
    { korean: "즐거움", uzbek: "quvonch" },
    { korean: "후련하다", uzbek: "yengil tortmoq" },
    { korean: "동의하다", uzbek: "1. (fikriga) qo'shilmoq 2. rozi bo'lmoq" },
    { korean: "바위", uzbek: "qoyatosh" },
    { korean: "발달", uzbek: "(개발) rivoj, taraqqiyot" },
    { korean: "제작", uzbek: "ishlab chiqarish" },
    { korean: "넘어가다", uzbek: "1. yiqilmoq 2. inqirozga uchramoq" },
    { korean: "죽이다", uzbek: "o'ldirmoq" },
    { korean: "기사", uzbek: "maqola" },
    { korean: "신선하다", uzbek: "yangi (masalliq)" },
    { korean: "침착하다", uzbek: "bosiq, og'ir-vazmin" },
    { korean: "활용하다", uzbek: "foydalanmoq" },
    { korean: "타인", uzbek: "boshqa odam" },
    { korean: "진화", uzbek: "rivojlanish (evolutsiya)" },
    { korean: "저해하다", uzbek: "g’ov bo’lmoq, to’siq bo’lmoq" },
    { korean: "심리학", uzbek: "psixologiya yo'nalishi" },
    { korean: "공연장", uzbek: "spektakl joyi" },
    { korean: "대중적", uzbek: "ommaviy" },
    { korean: "의논", uzbek: "muhokama" },
    { korean: "채식", uzbek: "vegetarian dietasi" },
    { korean: "성적", uzbek: "yutuq, baho" },
    { korean: "미래가 밝다", uzbek: "kelajagi yorug’" },
    { korean: "안도", uzbek: "dam oladigan joy" },
    { korean: "흘리다", uzbek: "oqizmoq, to’kmoq (땀을 \\~)" },
    { korean: "당사자", uzbek: "tomonlar / qatnashuvchi" },
    { korean: "구체적", uzbek: "aniq, batafsil" },
    { korean: "공유", uzbek: "umumiy, jamoat" },
    { korean: "손쉽다", uzbek: "oson" },
    { korean: "옥상", uzbek: "tom" },
    { korean: "평론", uzbek: "tanqid" },
    { korean: "기록", uzbek: "qayd" },
    { korean: "애석하다", uzbek: "g’amgin" },
    { korean: "친환경", uzbek: "eko, ekologik toza" },
    { korean: "소극적", uzbek: "nofaol, passiv" },
    { korean: "연하다", uzbek: "1. yengil (kosmetikada, pishirishda) 2. yumshoq (go’sht)" },
    { korean: "비다", uzbek: "bo'sh" },
    { korean: "대다", uzbek: "1. tegkizmoq (상처에 손을 \\~) 2. yetmoq (영어에서 그에 \\~할 사람이 없다), 3. -에 손을 대다 - ga qo'l urmoq" },
    { korean: "이전", uzbek: "oldin" },
    { korean: "도서", uzbek: "kitoblar" },
    { korean: "굳이", uzbek: "qattiq (xoxlamoq, ishonmoq va hkz)" },
    { korean: "긁다", uzbek: "qashimoq (머리를 \\~, 벌레 물린 데를 \\~)" },
    { korean: "마땅하다", uzbek: "mos bo'lmoq" },
    { korean: "극심하다", uzbek: "kuchli (\\~ 더위, 추위, 피해)" },
    { korean: "들어서다", uzbek: "kirmoq" },
    { korean: "사이가 좋다", uzbek: "yaqin, munosabatlari yaxshi" },
    { korean: "노선", uzbek: "marshrut, yo’nalish" },
    { korean: "경매", uzbek: "auksion" },
    { korean: "법규", uzbek: "qonun va qoida" },
    { korean: "위험하다", uzbek: "xavfli" },
    { korean: "여유롭다", uzbek: "yetarlicha (vaqt / joy / pul bo’lmoq)" },
    { korean: "송금하다", uzbek: "pul o’tkazmoq" },
    { korean: "예금", uzbek: "omonat" },
    { korean: "예산", uzbek: "byudjet" },
    { korean: "영양", uzbek: "ozuqa" },
    { korean: "수정하다", uzbek: "o'zgartirmoq, to'g'rilamoq" },
    { korean: "치통", uzbek: "tish og'riqi" },
    { korean: "멋", uzbek: "did, ta'b" },
    { korean: "달리하다", uzbek: "farq qilmoq (의견을 \\~)" },
    { korean: "범위", uzbek: "ko’lam, doira (지식의 \\~)" },
    { korean: "개별", uzbek: "alohida, yakka" },
    { korean: "버리다", uzbek: "tashlamoq" },
    { korean: "약점", uzbek: "zaif tarafi" },
    { korean: "배달", uzbek: "yetkazib berish" },
    { korean: "노력하다", uzbek: "harakat atmoq" },
    { korean: "이만", uzbek: "bunday" },
    { korean: "주제", uzbek: "mavzu" },
    { korean: "과로", uzbek: "o’zini urintirib qo’yish, ortiqcha ishlash" },
    { korean: "매다", uzbek: "bog’lamoq" },
    { korean: "규제", uzbek: "nazorat" },
    { korean: "앞날", uzbek: "kelajakdagi kunlar" },
    { korean: "난청", uzbek: "quloqi og'ir" },
    { korean: "재우다", uzbek: "uxlatmoq" },
    { korean: "버려지다", uzbek: "tashlanmoq" },
    { korean: "한편", uzbek: "1. bir taraf 2. bir vaqtni o’zida" },
    { korean: "통제하다", uzbek: "nazorat qilmoq, boshqarmoq" },
    { korean: "눈길을 끌다", uzbek: "e’tiborni tortmoq" },
    { korean: "흐릿하다", uzbek: "xira (날씨, 날, 기억, 눈 va hkz)" },
    { korean: "목적", uzbek: "maqsad" },
    { korean: "경고하다", uzbek: "ogohlantirmoq" },
    { korean: "사고 현장", uzbek: "xodisa joyi" },
    { korean: "지켜보다", uzbek: "kuzatmoq" },
    { korean: "대기하다", uzbek: "kutmoq" },
    { korean: "연주하다", uzbek: "chalmoq" },
    { korean: "흔하다", uzbek: "oddiy" },
    { korean: "거론되다", uzbek: "ta'kidlanmoq, muhokama qilinmoq" },
    { korean: "조심하다", uzbek: "extiyot bo’lmoq" },
    { korean: "일관되다", uzbek: "bardavom, o'zgarmas" },
    { korean: "타다", uzbek: "minmoq" },
    { korean: "학비", uzbek: "kontrakt to'lovi" },
    { korean: "조사하다", uzbek: "tekshirmoq, tekshiruv o'tkazmoq" },
    { korean: "또한", uzbek: "shu bilan birga" },
    { korean: "약하다", uzbek: "zaif, kuchsiz" },
    { korean: "보수", uzbek: "oylik" },
    { korean: "세탁기", uzbek: "kir yuvish mashinasi" },
    { korean: "미각", uzbek: "tam sezish qobiliyati" },
    { korean: "습득하다", uzbek: "1. o’rganmoq 2. topib olmoq" },
    { korean: "찾다", uzbek: "1. qidirmoq 2. topmoq" },
    { korean: "평범하다", uzbek: "oddiy" },
    { korean: "편안하다", uzbek: "qulay (shinam ma'nosida)" },
    { korean: "유창하다", uzbek: "ravon (tilga nisbatan)" },
    { korean: "복학생", uzbek: "o'qishni qayta tiklagan talaba" },
    { korean: "유혹하다", uzbek: "o'ziga tortmoq, yo'ldan ozdirmoq" },
    { korean: "흔들리다", uzbek: "tebranmoq, silkinmoq" },
    { korean: "이기적", uzbek: "egoist, faqat o’zni o’ylaydigan" },
    { korean: "기온", uzbek: "harorat" },
    { korean: "대상", uzbek: "1. mo’ljal 2. katta mukofot" }
];
